# Data Analytics and Visualization (part 1)

The best way to learn programming is by solving real-world problems. That's why this course is designed around a common and practical scientific task: ***data analysis***.

Throughout this part of the workshop, we will work with a dataset that contains valuable information about the physical oceanography at Potter Cove, located on King George Island in Antarctica.

This dataset includes measurements collected using a device known as a CTD, which stands for Conductivity, Temperature, and Depth. The data was gathered between January 4 and February 3, 1994, and includes important details such as:

- ***water depth [meters]***
- ***temperature [Celsius]***
- ***salinity levels***
- ***water density [kg/m**3]***

In total, we have 774 individual measurements from this study, which will help us understand the ocean conditions in this unique area.

## Load Pandas

**Python** doesn’t load all of the libraries available to it by default. We have to add an import statement to our code in order to use library functions.

In [1]:
#Import the pandas library as 'pd'
import pandas as pd

When we invoke a function from a library we use the following syntax: **LibraryName.FunctionName**, in this case we can call it **pandas.FunctionName**

By giving *pandas* a *nickname* such as **pd**, it makes our lives easier now that we can call the function **pd.FunctionName** instead.
This smart trick allows us to avoid typing out the full “pandas” keyword every time we use a function from the Pandas library.

## Read CSV file using Pandas

Pandas  can be used to import data stored in a Comma-Separated Values (CSV) file format. CSV is a common and simple way of structuring tabular data, where each line corresponds to a row and the values within a line are separated by commas.

In [2]:
# Read csv file using pandas

#Step 1: Specify File Path
file_path = 'data/ocean_data_potter_cove.csv'

#Step 2: Read CSV file
pd.read_csv(file_path)

           Date  Water_Depth  Temperature  Salinity_Level  Water_Density
0    1994-01-04          0.1         1.10           32.88          26.81
1    1994-01-04          0.2         1.02           32.90          26.82
2    1994-01-04          0.4         0.92           33.00          26.92
3    1994-01-04          0.6         0.91           33.08          26.98
4    1994-01-04          0.8         0.87           33.06          26.96
..          ...          ...          ...             ...            ...
769  1994-02-03         38.3         0.84           34.19          27.88
770  1994-02-03         38.6         0.83           34.19          27.88
771  1994-02-03         38.7         0.83           34.19          27.88
772  1994-02-03         39.0         0.83           34.19            NaN
773  1994-02-03         39.1         0.83           34.19          27.88

[774 rows x 5 columns]

This code returns an overview of how the dataset looks like, returning the first and last five rows.

The **read_csv** function has successfully processed our file but has not yet stored it into memory for further processing and analysis, so to do this we will add a new variable called “df”, short for dataframe:

In [3]:
# Save csv file to memory using pandas
df =  pd.read_csv(file_path)
df

           Date  Water_Depth  Temperature  Salinity_Level  Water_Density
0    1994-01-04          0.1         1.10           32.88          26.81
1    1994-01-04          0.2         1.02           32.90          26.82
2    1994-01-04          0.4         0.92           33.00          26.92
3    1994-01-04          0.6         0.91           33.08          26.98
4    1994-01-04          0.8         0.87           33.06          26.96
..          ...          ...          ...             ...            ...
769  1994-02-03         38.3         0.84           34.19          27.88
770  1994-02-03         38.6         0.83           34.19          27.88
771  1994-02-03         38.7         0.83           34.19          27.88
772  1994-02-03         39.0         0.83           34.19            NaN
773  1994-02-03         39.1         0.83           34.19          27.88

[774 rows x 5 columns]

If the dataset contains many samples then it is a good idea to use the **head()** function of Pandas to see the first few samples of the dataset. The function head() by itself returns the first 5 rows, but we can also specify how many rows we want to display by adding a number as a parameter in the function: **head(*10*)**

In [4]:
#Print the first rows of our dataframe
df.head(10)

         Date  Water_Depth  Temperature  Salinity_Level  Water_Density
0  1994-01-04          0.1         1.10           32.88          26.81
1  1994-01-04          0.2         1.02           32.90          26.82
2  1994-01-04          0.4         0.92           33.00          26.92
3  1994-01-04          0.6         0.91           33.08          26.98
4  1994-01-04          0.8         0.87           33.06          26.96
5  1994-01-04          1.0         0.80           33.14          27.03
6  1994-01-04          1.2         0.76           33.27          27.14
7  1994-01-04          1.5         0.74           33.37          27.22
8  1994-01-04          1.7         0.74           33.44          27.28
9  1994-01-04          1.9         0.75           33.45          27.29

We can also check what kind of things **df** contains using **dtypes**. What kind of data types our dataframe contains:

In [5]:
#Print the data types in the dataframe
df.dtypes

Date               object
Water_Depth       float64
Temperature       float64
Salinity_Level    float64
Water_Density     float64
dtype: object

## Explore the DataFrame Object

Let’s explore the DataFrame Object further. We will be using both methods and attributes.

**Methods** are functions that we can apply to the DataFrame to perform specific operations. They usually require parentheses. If we wish to see the information of a dataframe, we can use the **info()** function:

In [6]:
#Print dataframe information
info = df.info()
print(info)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 774 entries, 0 to 773
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            774 non-null    object
 1   Water_Depth     765 non-null    float64
 2   Temperature     769 non-null    float64
 3   Salinity_Level  768 non-null    float64
 4   Water_Density   770 non-null    float64
dtypes: float64(4), object(1)
memory usage: 30.4+ KB
None

This summary provides valuable information about the DataFrame’s structure, data types, and the presence of missing values. It’s a quick overview that helps you understand the content and characteristics of the DataFrame.

We can use the **unique()** function to identify the distinct values within a column or an array.

In [7]:
#Identify distinct values within a column
pd.unique(df['Date'])

array(['1994-01-04', '1994-01-11', '1994-01-19', '1994-01-25',
       '1994-02-03'], dtype=object)

It returns the unique values in the **Date/Time** column.

**Attributes** are properties of the DataFrame that provide information about its characteristics. They don’t require parentheses. If we wish to see the shape, number of rows and columns, of the dataframe we can use the **shape** attribute:

In [8]:
# Get the shape of the DataFrame (attribute)
shape = df.shape
print(shape) #Output: (rows, columns)

(774, 5)

### Exercise 1 (Try it yourself!)
What would be the output of the following commands?
-  df.tail()
-  df.columns

In [9]:
#Your exercise code goes here

## Selecting Data Using Labels

To select a single column, use the DataFrame’s name followed by the column label in square brackets **['ColumnLabel']**.

In [10]:
# Select the "Temperature" column
df['Temperature']

0      1.10
1      1.02
2      0.92
3      0.91
4      0.87
       ...
769    0.84
770    0.83
771    0.83
772    0.83
773    0.83
Name: Temperature, Length: 774, dtype: float64

We can also use the column name as an *attribute* to access data from that column using **df.Temperature**

In [11]:
# Select the 'Temperature' column as an attribute
df.Temperature

0      1.10
1      1.02
2      0.92
3      0.91
4      0.87
       ...
769    0.84
770    0.83
771    0.83
772    0.83
773    0.83
Name: Temperature, Length: 774, dtype: float64

To select multiple columns, enclose the column labels in double square brackets **[['Column1', 'Column2']]**.

In [12]:
# Select the 'Date' and 'Temperature' columns
df[['Date', 'Temperature']]

           Date  Temperature
0    1994-01-04         1.10
1    1994-01-04         1.02
2    1994-01-04         0.92
3    1994-01-04         0.91
4    1994-01-04         0.87
..          ...          ...
769  1994-02-03         0.84
770  1994-02-03         0.83
771  1994-02-03         0.83
772  1994-02-03         0.83
773  1994-02-03         0.83

[774 rows x 2 columns]

We can also create a new object and store the result, and later we can access the result from the object.

In [13]:
# Select the 'Date' and 'Temperature' columns and store in a object
date_temperature_columns = df[['Date', 'Temperature']]
print("\nSelected Date and Temperature columns:\n", date_temperature_columns)

Selected Date and Temperature columns:
            Date  Temperature
0    1994-01-04         1.10
1    1994-01-04         1.02
2    1994-01-04         0.92
3    1994-01-04         0.91
4    1994-01-04         0.87
..          ...          ...
769  1994-02-03         0.84
770  1994-02-03         0.83
771  1994-02-03         0.83
772  1994-02-03         0.83
773  1994-02-03         0.83

[774 rows x 2 columns]

### Exercise 2 (Try it yourself!)
What happens if you ask for a column that doesn’t exist?
-  df['Time']

In [14]:
#Your exercise code goes here

## Extracting Range-based Subsets (Slicing)
Slicing is a technique used to extract a portion or subset of elements from a sequence, such as a list or string. It allows us to specify a range of indices to retrieve a subset of the data.

-  Getting Specific Elements
-  Getting a Set of Elements
-  Getting First Few Elements
-  Getting Last Few Elements

Let's go through a simple example of a list before moving back to dataframes:

In [15]:
# Sample list
my_list = [10, 20, 30, 40, 50, 60, 70, 80]

# Getting specific elements
element_at_index_2 = my_list[2]
print("Element at index 2:", element_at_index_2)

# Getting a set of elements
subset = my_list[2:5] # index 5 is not included
print("Subset from index 2 to 4:", subset)

# Getting first few elements
first_three_elements = my_list[:3]
print("First three elements:", first_three_elements)

# Getting last few elements
last_two_elements = my_list[-2:]
print("Last two elements:", last_two_elements)

Element at index 2: 30
Subset from index 2 to 4: [30, 40, 50]
First three elements: [10, 20, 30]
Last two elements: [70, 80]

### Exercise 3 (Try it yourself!)
What would be the output of the following command
-  my_list[len(my_list)]

In [16]:
# Your exercise code goes here

## Slicing Rows and Columns
Slicing rows and columns simultaneously involves using **.loc** or **.iloc** and specifying the row indices and column labels or indices we want to include.

-  **.loc** is label-based indexing, meaning we specify the row and column labels.
-  **.iloc** is position-based indexing, meaning we use integer-positions indices for rows and columns.

#### Using .loc

In [17]:
# Slice rows 1 to 3 and columns 'Date' and 'Salinity_Level' using .loc
sliced_rows_columns_loc = df.loc[0:2, ['Date', 'Salinity_Level']] # Second part of range it's included
print("Sliced Rows and Columns using .loc:\n", sliced_rows_columns_loc)

Sliced Rows and Columns using .loc:
          Date  Salinity_Level
0  1994-01-04           32.88
1  1994-01-04           32.90
2  1994-01-04           33.00

Now, if we want to select **‘Date’, ’Water_Depth’, and ‘Salinity_Level’** columns with row labels **“1, 3, 4”**, we can also do this using the below code:

In [18]:
# Slice rows “1, 3, 4” and columns ‘Date’, ’Water_Depth’, and ‘Salinity_Level’
sliced_rows_columns_loc2 = df.loc[[1, 3, 4], ['Date', 'Water_Depth','Salinity_Level']]
print("Sliced Rows and Columns using .loc:\n", sliced_rows_columns_loc2)

Sliced Rows and Columns using .loc:
          Date  Water_Depth  Salinity_Level
1  1994-01-04          0.2           32.90
3  1994-01-04          0.6           33.08
4  1994-01-04          0.8           33.06

### Using .iloc:

In [19]:
# Slice rows 1 to 3 and columns at index 1 to 3 using .iloc
sliced_rows_columns_iloc = df.iloc[1:4, 1:4]
print("Sliced Rows and Columns using .iloc:\n", sliced_rows_columns_iloc)

Sliced Rows and Columns using .iloc:
    Water_Depth  Temperature  Salinity_Level
1          0.2         1.02           32.90
2          0.4         0.92           33.00
3          0.6         0.91           33.08

In both cases, using *.loc* or *.iloc*, the first argument specifies the rows to include, and the second argument specifies the columns to include.

## Subsetting Data using Criteria
Subsetting data using criteria involves selecting a subset of rows from a DataFrame based on specific conditions. This is often done to filter out rows that meet certain criteria or to focus on specific data points that are relevant to our analysis.

We can use conditional statements to filter rows based on specific criteria. The condition is typically applied to a column, and rows meeting the condition are retained.

For example, let’s say we want to subset the DataFrame to only include samples with water depth greater than 25 meters:

In [20]:
# Subset data for samples with Water_Depth > 25
subset_water_depth__25 = df[df['Water_Depth'] > 25]
print("Subset of samples with Water Depth > 25:\n", subset_water_depth__25)

Subset of samples with Water Depth > 25:
            Date  Water_Depth  Temperature  Salinity_Level  Water_Density
131  1994-01-04         25.2         0.56           34.13          27.84
132  1994-01-04         25.3         0.55           34.13          27.85
133  1994-01-04         25.5         0.55           34.13          27.85
134  1994-01-04         25.7         0.55           34.13          27.85
135  1994-01-04         25.9         0.55             NaN          27.85
..          ...          ...          ...             ...            ...
769  1994-02-03         38.3         0.84           34.19          27.88
770  1994-02-03         38.6         0.83           34.19          27.88
771  1994-02-03         38.7         0.83           34.19          27.88
772  1994-02-03         39.0         0.83           34.19            NaN
773  1994-02-03         39.1         0.83           34.19          27.88

[229 rows x 5 columns]

Also, we can combine multiple criteria using logical operators such as **&** *(AND)* and **|** *(OR)* to create more complex conditions.

For instance, to subset the DataFrame for samples with water depth greater than 25 meters and salinity levels greater than 33.

In [21]:
# Subset data for samples with 'Water_Depth' > 25 and 'Salinity_Level' > 33
subset_depth_salinity = df[(df['Water_Depth'] > 25) & (df['Salinity_Level'] > 33)]
print("Subset of samples with 'Water_Depth' > 25 and 'Salinity_Level' > 33:\n", subset_depth_salinity)

Subset of samples with 'Water_Depth' > 25 and 'Salinity_Level' > 33:
            Date  Water_Depth  Temperature  Salinity_Level  Water_Density
131  1994-01-04         25.2         0.56           34.13          27.84
132  1994-01-04         25.3         0.55           34.13          27.85
133  1994-01-04         25.5         0.55           34.13          27.85
134  1994-01-04         25.7         0.55           34.13          27.85
136  1994-01-04         26.1         0.55           34.13          27.85
..          ...          ...          ...             ...            ...
769  1994-02-03         38.3         0.84           34.19          27.88
770  1994-02-03         38.6         0.83           34.19          27.88
771  1994-02-03         38.7         0.83           34.19          27.88
772  1994-02-03         39.0         0.83           34.19            NaN
773  1994-02-03         39.1         0.83           34.19          27.88

[226 rows x 5 columns]

We can also use the **~** symbol to negate a condition. For example, to subset the DataFrame for samples with a water depth less than or equal to 25 meters:

In [22]:
# Subset data for individuals with depth <= 25
subset_depth_le_25 = df[~(df['Water_Depth'] > 25)]
print("Subset of samples with water depth <= 25:\n", subset_depth_le_25)

Subset of samples with water depth <= 25:
            Date  Water_Depth  Temperature  Salinity_Level  Water_Density
0    1994-01-04          0.1         1.10           32.88          26.81
1    1994-01-04          0.2         1.02           32.90          26.82
2    1994-01-04          0.4         0.92           33.00          26.92
3    1994-01-04          0.6         0.91           33.08          26.98
4    1994-01-04          0.8         0.87           33.06          26.96
..          ...          ...          ...             ...            ...
712  1994-02-03         23.5         0.90           34.17          27.86
713  1994-02-03         23.8         0.90           34.17          27.86
714  1994-02-03         24.1         0.89           34.18          27.87
715  1994-02-03         24.4         0.89           34.15          27.85
716  1994-02-03         24.8         0.88           34.16          27.85

[545 rows x 5 columns]

The **isin()** function is used to filter data based on whether values are present in a specified list or iterable. It’s a convenient way to subset data when we want to select rows that match specific values for a particular column.

Let’s say we want to select rows where the **‘Date’** column has values **‘1994-01-04’** or **‘1994-01-11’**:

In [23]:
# Subsetting data using isin() function
subset_date = df[df['Date'].isin(['1994-01-04', '1994-01-11'])]
print("Subset of data with 'Data' values '1994-01-04' or '1994-01-11':\n", subset_date)

Subset of data with 'Data' values '1994-01-04' or '1994-01-11':
            Date  Water_Depth  Temperature  Salinity_Level  Water_Density
0    1994-01-04          0.1         1.10           32.88          26.81
1    1994-01-04          0.2         1.02           32.90          26.82
2    1994-01-04          0.4         0.92           33.00          26.92
3    1994-01-04          0.6         0.91           33.08          26.98
4    1994-01-04          0.8         0.87           33.06          26.96
..          ...          ...          ...             ...            ...
365  1994-01-11         33.9         0.83           34.06          27.77
366  1994-01-11         34.0         0.83           34.05          27.77
367  1994-01-11         34.2         0.83           34.06          27.78
368  1994-01-11         34.4         0.83           34.06          27.77
369  1994-01-11         11.5         1.33           32.16          26.22

[370 rows x 5 columns]

**isnull()** and **notnull()** functions are used to detect missing (NaN) values in a DataFrame. **isnull()** returns a DataFrame of the same shape as the input, with True values indicating missing values. **notnull()** returns the opposite.

Let’s say we want to select rows where the ‘Water_Depth’ column *has missing values*:

In [24]:
# Subsetting data using isnull() function
subset_missing_depth = df[df['Water_Depth'].isnull()]
print("Subset of data with missing 'Water_Depth' values:\n", subset_missing_depth)

Subset of data with missing 'Water_Depth' values:
            Date  Water_Depth  Temperature  Salinity_Level  Water_Density
15   1994-01-04          NaN         1.13           33.71          27.48
54   1994-01-04          NaN         1.11           33.94          27.66
70   1994-01-04          NaN         0.90           34.00          27.72
155  1994-01-04          NaN         0.51           34.13          27.85
234  1994-01-11          NaN         1.06           33.82          27.57
333  1994-01-11          NaN         0.83           34.06          27.77
389  1994-01-19          NaN         1.50           33.70          27.45
468  1994-01-19          NaN         1.18           34.07          27.77
674  1994-02-03          NaN         1.06           34.07          27.77

### Revisiting .loc vs. .iloc

Now that we have filtered out some data, let's revisit `df.loc` (select by label) vs. `df.iloc` (select by position) again.
```python
subset_missing_depth.loc[15:70]

subset_missing_depth.iloc[0:3]
```

In [25]:
subset_missing_depth.loc[15:70]

          Date  Water_Depth  Temperature  Salinity_Level  Water_Density
15  1994-01-04          NaN         1.13           33.71          27.48
54  1994-01-04          NaN         1.11           33.94          27.66
70  1994-01-04          NaN         0.90           34.00          27.72

In [26]:
subset_missing_depth.iloc[0:3]

          Date  Water_Depth  Temperature  Salinity_Level  Water_Density
15  1994-01-04          NaN         1.13           33.71          27.48
54  1994-01-04          NaN         1.11           33.94          27.66
70  1994-01-04          NaN         0.90           34.00          27.72

Let’s say we want to select rows where the ‘Water_Depth’ column *does not have missing values*:

In [27]:
# Subsetting data using notnull() function
subset_notMissing_depth = df[df['Water_Depth'].notnull()]
print("Subset of data without missing 'Water_Depth' values:\n", subset_notMissing_depth)

Subset of data without missing 'Water_Depth' values:
            Date  Water_Depth  Temperature  Salinity_Level  Water_Density
0    1994-01-04          0.1         1.10           32.88          26.81
1    1994-01-04          0.2         1.02           32.90          26.82
2    1994-01-04          0.4         0.92           33.00          26.92
3    1994-01-04          0.6         0.91           33.08          26.98
4    1994-01-04          0.8         0.87           33.06          26.96
..          ...          ...          ...             ...            ...
769  1994-02-03         38.3         0.84           34.19          27.88
770  1994-02-03         38.6         0.83           34.19          27.88
771  1994-02-03         38.7         0.83           34.19          27.88
772  1994-02-03         39.0         0.83           34.19            NaN
773  1994-02-03         39.1         0.83           34.19          27.88

[765 rows x 5 columns]

## Calculating Statistics from Pandas DataFrame
We can use Pandas DataFrame’s built-in methods to quickly generate summary statistics for our data. Such as, we can use the **describe()** function to get summary statistics for numerical columns like count, mean, standard deviation, minimum, and maximum.

In [28]:
# Print the summary statistics of the dataframe using describe()
summary = df.describe()
print(summary)

       Water_Depth  Temperature  Salinity_Level  Water_Density
count   765.000000   769.000000      768.000000     770.000000
mean     17.707843     1.020455       33.935768      27.664494
std      10.898713     0.291755        0.324256       0.268713
min       0.000000     0.470000       31.430000      25.610000
25%       8.300000     0.830000       33.880000      27.610000
50%      17.100000     0.980000       34.030000      27.740000
75%      26.800000     1.210000       34.090000      27.790000
max      39.700000     1.650000       34.200000      27.890000

If we want to calculate the standard deviation of a numerical column we can use **std()** function.

In [29]:
#Print the standard deviation of the Salinity_Level column using std()
salinity_std = df['Salinity_Level'].std()
print("Salinity_Level Standard Deviation:", salinity_std)

Salinity_Level Standard Deviation: 0.3242557353939066

There are many more statistics formulas that you can use, I encourage you to check out the following resources:
-  https://www.tutorialspoint.com/python_pandas/python_pandas_descriptive_statistics.htm
-  https://www.scaler.com/topics/pandas/statistical-functions-in-pandas/

I promise you will have fun!

## Groups in Pandas

Frequently, there’s a need to compute summary statistics based on subsets or specific attributes within our dataset. For instance, we might wish to find the summary statistics of the water density of all the samples, we can do it using the following code:

In [30]:
#Return summary statistics of the Water_Density column
df['Water_Density'].describe()

count    770.000000
mean      27.664494
std        0.268713
min       25.610000
25%       27.610000
50%       27.740000
75%       27.790000
max       27.890000
Name: Water_Density, dtype: float64

Again, we might also want to get only specific information, like the maximum:

In [31]:
#Return the maximum value of the Water_Density column
df['Water_Density'].max()

np.float64(27.89)

or we can get the average income of all individuals:

In [32]:
#Return the average Water_Density of all samples
df['Water_Density'].mean()

np.float64(27.664493506493507)

However, when the intention is to summarize data based on one or more variables, such as Date, the Pandas library offers the **.groupby** method. Once a DataFrame is grouped using this approach, we have the ability to compute summary statistics of the selected grouping.

In [33]:
# Group data by Date
grouped_data = df.groupby('Date')

# Provide the mean for each numeric column by Date
grouped_data.mean(numeric_only=True)

            Water_Depth  Temperature  Salinity_Level  Water_Density
Date
1994-01-04    19.066667     0.801451       33.973575      27.705641
1994-01-11    17.074419     0.922081       33.976590      27.703103
1994-01-19    16.064789     1.360140       33.855524      27.582727
1994-01-25    16.290000     1.331200       33.736500      27.484545
1994-02-03    19.111321     0.893188       34.042956      27.757358

## Basic Math with Pandas
If desired, it’s entirely possible to perform mathematical operations, such as addition or division, on an entire column of our dataframe.


Let's multiply the Temperature column by 2:

In [34]:
# Multiply all Temperature values by 2
df['Temperature']*2

0      2.20
1      2.04
2      1.84
3      1.82
4      1.74
       ...
769    1.68
770    1.66
771    1.66
772    1.66
773    1.66
Name: Temperature, Length: 774, dtype: float64

## Concatenating DataFrames
Concatenating DataFrames refers to combining two or more DataFrames along a particular axis (either rows or columns) to create a single larger DataFrame. This is useful when we have data split across multiple DataFrames and we want to consolidate them into one for analysis or processing.

In Pandas, we can use the **concat()** function to concatenate DataFrames. This function provides various options to control how the concatenation should be performed.

Let’s say we have two DataFrames, **df1** and **df2**, and we want to concatenate them vertically (along rows):

In [35]:
#Concatenate df1 and df2 vertically (along rows)

# Sample DataFrames
data1 = {'A': [1, 2, 3], 'B': [4, 5, 6]}
data2 = {'A': [7, 8, 9], 'B': [10, 11, 12]}
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

# Concatenate DataFrames vertically
concatenated_df = pd.concat([df1, df2], ignore_index=True)
print("Concatenated DataFrame:\n", concatenated_df)

Concatenated DataFrame:
    A   B
0  1   4
1  2   5
2  3   6
3  7  10
4  8  11
5  9  12

In this example, **pd.concat()** is used to concatenate df1 and df2 vertically into concatenated_df. The **ignore_index=True** argument ensures that the index is reset after concatenation.

We can also concatenate DataFrames **horizontally** by specifying **axis=1** as an argument to **pd.concat()**. This will merge the DataFrames along columns.

In [36]:
#Concatenate df1 and df2 horizontally
import pandas as pd

# Sample DataFrames
data1 = {'A': [1, 2, 3], 'B': [4, 5, 6]}
data2 = {'C': [7, 8, 9], 'D': [10, 11, 12]}
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

# Concatenate DataFrames horizontally
concatenated_df_horizontal = pd.concat([df1, df2], axis=1)
print("Horizontally Concatenated DataFrame:\n", concatenated_df_horizontal)

Horizontally Concatenated DataFrame:
    A  B  C   D
0  1  4  7  10
1  2  5  8  11
2  3  6  9  12

### Exercise 4 (Try it yourself!)
Consider two DataFrames, df1 and df2, with the following data:
```
import pandas as pd
data1 = {'A': [1, 2, 3], 'B': [4, 5, 6]}
data2 = {'A': [7, 8, 9], 'B': [10, 11, 12]}
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
```

What will be the output of the following code:
```
result = pd.concat([df1, df2], axis=1)
print(result)
```

Select the correct answer ***(without running the code)***:

a) The concatenated DataFrame with columns A, B, A, B

b) An error will occur because columns A and B are duplicated

c) The concatenated DataFrame with columns A, B, C, D

In [37]:
data1 = {'A': [1, 2, 3], 'B': [4, 5, 6]}
data2 = {'A': [7, 8, 9], 'B': [10, 11, 12]}
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
result = pd.concat([df1, df2], axis=1)
print(result)

   A  B  A   B
0  1  4  7  10
1  2  5  8  11
2  3  6  9  12

## Saving Pandas DataFrame

We can save a Pandas DataFrame to various file formats using different methods provided by Pandas. Before we move forward with saving  a pandas dataframe, let’s first create a new directory called “Results” within the directory that contains your code.

Here are some commonly used methods to save a DataFrame:
-  CSV Format: To save a DataFrame to a CSV file, we can use the to_csv() method:

In [38]:
# Save DataFrame to CSV file
output_path = 'Results/output.csv'
df.to_csv(output_path, index=False)

This will save the DataFrame to a CSV file named ‘output.csv’ inside a directory called “Results”, without including the index.

-  Excel Format: To save a DataFrame to an Excel file, we can use the to_excel() method:

In [39]:
# Save DataFrame to Excel file
output_path = 'Results/output.xlsx'
df.to_excel(output_path, index=False)

This will save the DataFrame to an Excel file named ‘output.xlsx’  inside a directory called “Results”, without including the index.

-  Other Formats: Pandas supports various other formats, including JSON, Parquet, HDF5, and more. We can use the appropriate method based on the desired format:

    -   JSON: df.to_json("output.json", orient="records")
    -   Parquet: df.to_parquet("output.parquet")
    -   HDF5: df.to_hdf("output.h5", key="data")

Make sure to replace ‘output’ with your desired file name and extension.