# Data Analytics and Visualization (part 2)

## Data Cleaning and Preparation

Data Cleaning involves identifying and rectifying errors, inconsistencies, and inaccuracies within the dataset. By eliminating missing values, outliers, and redundant information, data quality is enhanced, leading to more accurate and reliable insights.

Data cleaning and preparation helps to improve the overall efficiency of data analysis processes by ensuring that the dataset is more standardized and easier to work with. It also helps to reduce the risk of making faulty decisions based on flawed data.

### Handling Missing Values

Missing values in a dataset can hinder analysis and modeling. Pandas provides functions to handle missing values, such as  **fillna()**, which allows us to fill ***NaN*** values with a specific value or method.

Let's first start by importing our libraries:

In [2]:
#Import pandas library
import pandas as pd
import numpy as np

### [Exercise 1 (Try it yourself): Import appropriate package and load the dataset in *DAV2_Exercises* notebook]

Now, let's practice filling ***NaN*** values using **fillna()**:

In [4]:
# Creating a DataFrame with missing values
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [10, 20, 30, 40, 50]
}
df = pd.DataFrame(data)

# Before filling missing value
print("DataFrame before Filling Missing Values:\n",df)

# Filling missing values with 0
df_filled = df.fillna(0)

print("DataFrame with Missing Values Filled:\n", df_filled)

DataFrame before Filling Missing Values:
      A   B
0  1.0  10
1  2.0  20
2  NaN  30
3  4.0  40
4  5.0  50
DataFrame with Missing Values Filled:
      A   B
0  1.0  10
1  2.0  20
2  0.0  30
3  4.0  40
4  5.0  50

### [Exercise 2 (Try it yourself): Complete the 'handle_missing_values' in *DAV2_Exercises* notebook]

### Handling Outliers

Outliers are extreme values that can skew analysis and modeling results. Pandas can help us identify and handle outliers. In this example, we identify outliers using the **interquartile range (IQR)** method and remove them:

The **Interquartile Range (IQR)** is a measure of statistical dispersion, representing the range within which the middle 50% of the data lies. It is calculated as the difference between the 75th percentile (also called the third quartile, or Q3) and the 25th percentile (the first quartile, or Q1) of a dataset.

The IQR is useful in identifying the spread of data, and it is commonly used to detect outliers. Values that are significantly lower than Q1 or significantly higher than Q3 are often considered outliers.

Here's a breakdown of what the IQR represents in pandas and how to compute it:

**What IQR Represents**
-  Q1 (25th percentile): The value below which 25% of the data falls.
-  Q3 (75th percentile): The value below which 75% of the data falls.
-  IQR: The range between Q1 and Q3, calculated as IQR = Q3 - Q1.

**How to Calculate IQR in pandas:**
To calculate the IQR for a specific column in a pandas DataFrame, you can use the quantile method to get the 25th and 75th percentiles, and then subtract them to find the IQR.

In [9]:
# Creating a DataFrame with outliers
data = {
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 200, 50]
}
df = pd.DataFrame(data)

# Main Dataframe with Outliers
print("DataFrame with Outliers:\n", df)

# Identifying and handling outliers
q1 = df['B'].quantile(0.25)
q3 = df['B'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

number_outliers = df[
    (df['B'] < lower_bound) |
    (df['B'] > upper_bound)
]

print("\nNumber of existent outliers:", len(number_outliers))

df_no_outliers = df[(df['B'] >= lower_bound) & (df['B'] <= upper_bound)]

print("\nDataFrame with Outliers Removed:\n", df_no_outliers)

remaining_outliers = df_no_outliers[
    (df_no_outliers['B'] < lower_bound) |
    (df_no_outliers['B'] > upper_bound)
]

print("\nNumber of remaining outliers:", len(remaining_outliers))

DataFrame with Outliers:
    A    B
0  1   10
1  2   20
2  3   30
3  4  200
4  5   50

Number of existent outliers: 1

DataFrame with Outliers Removed:
    A   B
0  1  10
1  2  20
2  3  30
4  5  50

Number of remaining outliers: 0

In [4]:
df.describe()

              A           B
count  5.000000    5.000000
mean   3.000000   62.000000
std    1.581139   78.549348
min    1.000000   10.000000
25%    2.000000   20.000000
50%    3.000000   30.000000
75%    4.000000   50.000000
max    5.000000  200.000000

In [3]:
df_no_outliers.describe()

              A          B
count  4.000000   4.000000
mean   2.750000  27.500000
std    1.707825  17.078251
min    1.000000  10.000000
25%    1.750000  17.500000
50%    2.500000  25.000000
75%    3.500000  35.000000
max    5.000000  50.000000

**Code Explanation**
-  **q1** and **q3** are calculated using the **quantile()** function, representing the first and third quartiles of column ‘B’.
-  **q1** represents the value below which 25% of the data lies. For column ‘B’, **q1** would be the median of the first half of the sorted values, which is 15.
-  **q3** represents the value below which 75% of the data lies. For column ‘B’, **q3** would be the median of the second half of the sorted values, which is 50.
-  **iqr** (Interquartile Range) is computed as the difference between **q3** and **q1**.
-  **lower_bound** and **upper_bound** are calculated to define the thresholds beyond which data points are considered outliers. These bounds are defined as 1.5 times the IQR below q1 and above q3.
-  The line **df_no_outliers = df[(df['B'] >= lower_bound) & (df['B'] <= upper_bound)]** filters the DataFrame to keep only the rows where the values in column ‘B’ fall within the acceptable range, effectively removing the outliers.

### [Exercise 3 (Try it yourself): Complete the 'handle_outliers' function in *DAV2_Exercises* notebook]

### Dealing with Duplicate Data
Duplicate data can lead to misleading analysis. Pandas provides functions to detect and remove duplicate rows. Here’s how we can do it:

In [9]:
# Creating a DataFrame with duplicate data
data = {
    'A': [1, 2, 2, 3, 4, 4],
    'B': [10, 20, 20, 30, 40, 40]
}
duplicate_df = pd.DataFrame(data)

# Main DataFrame with duplicate data
print("DataFrame with Duplicates:\n", duplicate_df)

# Detecting and removing duplicated rows
duplicated_rows = duplicate_df[duplicate_df.duplicated()]

#Detecting and removing duplicated rows but keeping the first duplicate or the last duplicate
deduplicated_df = duplicate_df.drop_duplicates(keep = 'first')

print("Duplicated Rows:\n", duplicated_rows)
print("DataFrame after Dropping Duplicates:\n", deduplicated_df)

DataFrame with Duplicates:
    A   B
0  1  10
1  2  20
2  2  20
3  3  30
4  4  40
5  4  40
Duplicated Rows:
    A   B
2  2  20
5  4  40
DataFrame after Dropping Duplicates:
    A   B
0  1  10
1  2  20
3  3  30
4  4  40

### [Exercise 4 (Try it yourself): Complete the 'handle_duplicates' function in *DAV2_Exercises* notebook]

### Data Reshaping
Reshaping data is the process of transforming data from one format to another. In the context of data analysis and machine learning (ML), reshaping data often involves reorganizing it into a different structure that is better suited for analysis, visualization, or modeling. Reshaping can involve tasks such as pivoting, melting, stacking, unstacking, and more.

#### Wide to Long Format (Melting)
In this transformation, we convert a dataset from a wide format (many columns) to a long format (fewer columns) by melting or unpivoting it. This is useful when we have variables stored as columns and we want to gather them into a single column.

Melting data is useful for making it more suitable for analysis, especially when we want to compare or aggregate across different variables.

In [5]:
# Creating a Wide DataFrame
data = {
    'Depth (m)': [10, 50, 100],
    'Temperature (°C)': [15.0, 12.0, 8.5],
    'Salinity (ppt)': [33.0, 34.5, 36.0]
}
df = pd.DataFrame(data)

# Main Wide DataFrame
print("Original Wide DataFrame:\n", df)

# Melting the DataFrame to long format
df_long = pd.melt(df, id_vars=['Depth (m)'], value_vars=['Temperature (°C)', 'Salinity (ppt)'], 
                  var_name='Measurement', value_name='Value')

# After Melting the DataFrame
print("\nLong Format DataFrame:\n", df_long)

Original Wide DataFrame:
    Depth (m)  Temperature (°C)  Salinity (ppt)
0         10              15.0            33.0
1         50              12.0            34.5
2        100               8.5            36.0

Long Format DataFrame:
    Depth (m)       Measurement  Value
0         10  Temperature (°C)   15.0
1         50  Temperature (°C)   12.0
2        100  Temperature (°C)    8.5
3         10    Salinity (ppt)   33.0
4         50    Salinity (ppt)   34.5
5        100    Salinity (ppt)   36.0

**Code Explanation**
-  The **pd.melt()** function is used to transform the *df* DataFrame from wide format to long format.
-  **id_vars=['Depth (m)']** keeps the ‘Depth (m)’ column as an identifier. This means that each temperature and salinity reading will be linked to its depth.

- **value_vars=['Temperature (°C)', 'Salinity (ppt)']** tells the function which columns to transform. In this case, we are melting the ‘Temperature (°C)’ and ‘Salinity (ppt)’ columns into a single column. This helps us look at temperature and salinity together.

- **var_name='Measurement'** sets the name for the new column that will show what type of measurement each value represents (either temperature or salinity).

- **value_name='Value'** sets the name for the new column that will show the actual measurement values for temperature and salinity.

#### Long to Wide Format (Pivoting)
This transformation involves converting a long-format dataset back into a wide format by pivoting or spreading the values.

Pivoting is useful when we want to reshape data to make it easier to visualize or perform calculations on.

In [6]:
# Creating a Long DataFrame
data = {
    'Depth (m)': [10, 10, 50, 50],
    'Measurement': ['Temperature (°C)', 'Salinity (ppt)', 'Temperature (°C)', 'Salinity (ppt)'],
    'Value': [15.0, 33.0, 12.0, 34.5]
}
df_long = pd.DataFrame(data)

# Main Long DataFrame
print("Original Long DataFrame:\n", df_long)

# Pivoting the DataFrame
df_wide = df_long.pivot(index='Depth (m)', columns='Measurement', values='Value')
print("Wide Format DataFrame:\n", df_wide)

Original Long DataFrame:
    Depth (m)       Measurement  Value
0         10  Temperature (°C)   15.0
1         10    Salinity (ppt)   33.0
2         50  Temperature (°C)   12.0
3         50    Salinity (ppt)   34.5
Wide Format DataFrame:
 Measurement  Salinity (ppt)  Temperature (°C)
Depth (m)
10                     33.0              15.0
50                     34.5              12.0

**Code Explanation** 
-  The **df_long.pivot()** function is used to transform the df_long DataFrame from a long format to a wide format.
-  **index='Depth (m)'** specifies that the new DataFrame should use the 'Depth (m)' column as the row labels. This means each unique depth will become a row in the new DataFrame.
- **columns='Measurement'** tells the function to use the values in the 'Measurement' column (Temperature (°C) and Salinity (ppt)) as the column headers in the new DataFrame.
- **values='Value'** indicates that the actual data in the new DataFrame will come from the 'Value' column. So, it will fill the cells with the corresponding temperature and salinity values at each depth.

### Stacking and Unstacking
Stacking involves converting columns into rows, and unstacking is the reverse process. These operations can be useful for creating hierarchical indexes and dealing with multi-level data.

Stacking and unstacking can make data manipulation and analysis easier when dealing with multi-indexed data.

In [7]:
# Creating a DataFrame
data = {
    'Depth (m)': [10, 50],
    'Temperature (°C)': [15.0, 12.0],
    'Salinity (ppt)': [33.0, 34.5]
}
df = pd.DataFrame(data)

# Original DataFrame
print("Original DataFrame:\n", df)

# Set the DataFrame index using the Depth (m) column
df.set_index('Depth (m)', inplace=True)
# EXPLAIN inplace=True: When True, the operation modifies the original DataFrame df directly,
# without creating a new one. If inplace=False (or omitted), the function will return a new DataFrame 
# with the specified index while leaving the original DataFrame unchanged.

# Doing Stacking and Unstacking
stacked_df = df.stack()
unstacked_df = stacked_df.unstack()
print("Stacked DataFrame:\n", stacked_df)
print("Unstacked DataFrame:\n", unstacked_df)

Original DataFrame:
    Depth (m)  Temperature (°C)  Salinity (ppt)
0         10              15.0            33.0
1         50              12.0            34.5
Stacked DataFrame:
 Depth (m)
10         Temperature (°C)    15.0
           Salinity (ppt)      33.0
50         Temperature (°C)    12.0
           Salinity (ppt)      34.5
dtype: float64
Unstacked DataFrame:
            Temperature (°C)  Salinity (ppt)
Depth (m)
10                     15.0            33.0
50                     12.0            34.5

Stacking transforms a DataFrame from a wide format to a long format by moving a level of the column index to the row index. This operation is useful when you want to collapse hierarchical column indices into a simpler format.

Unstacking is the reverse of stacking. It transforms a DataFrame from a long format to a wide format by moving a level of the row index to the column index.

### Handling Inconsistent Data and Standardizing
Handling inconsistent data is a crucial step in data preprocessing to ensure the accuracy and reliability of our analysis or modeling. Inconsistent data refers to values that do not adhere to the expected format or constraints. This can include typos, varying representations, or unexpected values in categorical variables.

Suppose we have a dataset with a “Water_Type” column that contains variations of the categories “Freshwater”, “Salty”, and “Brackish”. To handle inconsistencies, we can standardize the values.

In [4]:
# Creating a DataFrame
data = {
    'Sample_ID': [1, 2, 3, 4, 5, 6],
    'Water_Type': ['Freshwater', 'salty', ' FRESHWATER', 'Salty ', 'brackish', 'BRACKISH']
}
df = pd.DataFrame(data)

# Original DataFrame
print("Original DataFrame:\n", df)

# Convert water type values to lowercase and standardize
df['Water_Type'] = df['Water_Type'].str.lower().str.strip().replace(
    {'freshwater': 'Freshwater', 'salty': 'Salty', 'brackish': 'Brackish'}
)
## can also be replaced for df['Water_Type'] = df['Water_Type'].str.strip().str.title() 
## in this case as there are no synonyms

print("DataFrame with Consistent Water Type Values:\n", df)

Original DataFrame:
    Sample_ID   Water_Type
0          1   Freshwater
1          2        salty
2          3   FRESHWATER
3          4       Salty
4          5     brackish
5          6     BRACKISH
DataFrame with Consistent Water Type Values:
    Sample_ID  Water_Type
0          1  Freshwater
1          2       Salty
2          3  Freshwater
3          4       Salty
4          5    Brackish
5          6    Brackish

**Code Explanation**
- **df['Water_Type']:** This gets the 'Water_Type' column from the DataFrame so we can work with it.

- **.str.lower()**: This changes all the text in the 'Water_Type' column to lowercase. This way, we make sure everything is written the same way.

- **.str.strip()**: This removes any extra spaces at the start or end of the text in the 'Water_Type' column. This helps avoid mistakes caused by those spaces.

- **.replace({'freshwater': 'Freshwater', 'salty': 'Salty', 'brackish': 'Brackish'})**: This replaces the words in the 'Water_Type' column. It changes 'freshwater' to 'Freshwater', 'salty' to 'Salty', and 'brackish' to 'Brackish'. This makes sure we have a consistent way of writing these terms.

- **Updating the Column**: Finally, we save the cleaned-up values back into the 'Water_Type' column. This makes the data neat and ready for analysis.

Now, suppose we have a dataset with a “Water_Type” column that contains various names for types of water, including some inconsistent spellings and synonyms. We want to standardize these water type names.

In [9]:
# Creating a DataFrame
data = {
    'ID': [1, 2, 3, 4, 5],
    'Water_Type': ['freshwater', 'salty', 'brackish', 'Salty', 'FRESHWATER']
}
df = pd.DataFrame(data)

# Original DataFrame
print("Original DataFrame:\n", df)

# Define a mapping for inconsistent water type names to standard names
water_type_mapping = {
    'freshwater': 'Freshwater',
    'salty': 'Salty',
    'brackish': 'Brackish'
}

# Apply the mapping to the Water_Type column
df['Water_Type'] = df['Water_Type'].str.lower().map(water_type_mapping)

print("DataFrame with Consistent Water Type Names:\n", df)

Original DataFrame:
    ID  Water_Type
0   1  freshwater
1   2       salty
2   3    brackish
3   4       Salty
4   5  FRESHWATER
DataFrame with Consistent Water Type Names:
    ID  Water_Type
0   1  Freshwater
1   2       Salty
2   3    Brackish
3   4       Salty
4   5  Freshwater

**Code Explanation**
- **Mapping Definition:** A dictionary called water_type_mapping is created to map the inconsistent names to standardized names. For example, both 'freshwater' and 'FRESHWATER' will be converted to 'Freshwater'.

- **Applying the Mapping:** We convert the ‘Water_Type’ column to lowercase and use .map(water_type_mapping) to replace the values based on our defined mapping.

- **Final Output:** Finally, we print the updated DataFrame, which now contains consistent water type names.

 **[Exercise 5 (Try it yourself): Complete the 'standardize_data' function to standardize the 'Species' column in the dataset in *DAV2_Exercises* notebook] ]**